mode_fin_task/company/urls.py
from django.urls import path
from company.views import *

urlpatterns = [
    path('', company_wise_list, name='company_wise_list'),
    path('activity_log/', activity_log, name='activity_log'),]

mode_fin_task/mode_fin_task/urls.py
from django.contrib import admin
from django.urls import path,include
from company.views import user_login, user_logout,recovery_creditional

urlpatterns = [
    path('admin/', admin.site.urls),
    path('company/', include('company.urls')),
    path('login/', user_login, name="user_login"),
    path('logout/', user_logout, name="user_logout"),
    path('recovery_creditional/', recovery_creditional, name="recovery_creditional"),

]

mode_fin_task/company/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save,post_delete
from django.dispatch import receiver

#comapny model extending the user model
class Company(models.Model):
    company_name = models.OneToOneField(User, on_delete=models.CASCADE)
    brand_name=models.CharField(max_length=100,null=True,blank=True)

    def __str__(self):
        return self.brand_name
# company_agent models to store the agent data and have ForeignKey key relationaship with Company
class company_agent(models.Model):
    company=models.ForeignKey(Company, null=True, blank=True, on_delete=models.CASCADE)
    company_agent_name=models.CharField(max_length=100,null=True,blank=True)
    no_of_call_attended=models.IntegerField(default=0)
    total_time_spent_for_call_attended=models.IntegerField(default=0)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
       return self.company_agent_name
#not useful ...just for expriments
class Admin_Log_Activity(models.Model):
    company_admin_name=models.ForeignKey(company_agent, null=True, blank=True, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    log_in_time=models.DateTimeField(null=True,blank=True)
    log_out_time=models.DateTimeField(null=True,blank=True)
    details_of_activity = models.TextField(null=True,blank=True)

    def __str__(self):
       return self.company_admin_name.company_agent_name
# Main_Log_Activity model to maintain admin activity log and have no ForeignKey relationship
class Main_Log_Activity(models.Model):
    user=models.CharField(max_length=100,null=True,blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    log_in_time=models.DateTimeField(null=True,blank=True)
    log_out_time=models.DateTimeField(null=True,blank=True)
    details_of_activity = models.TextField(null=True,blank=True)

    def __str__(self):
       return self.user

#when comapny angent will be craete by admin then created log will be maintain in activity log using this
def log_activity_add_agent(sender,instance,**kwargs):
    log_messages="%s is created by %s"%(instance.company_agent_name,instance.company.company_name.username)
    Main_Log_Activity.objects.create(user=instance.company.company_name.username,details_of_activity=log_messages)

#when comapny angent will be deleted by admin then created log will be maintain in activity log using this
def log_activity_delete_agent(sender,instance,**kwargs):
    log_messages="%s is deleted by %s"%(instance.company_agent_name,instance.company.company_name.username)
    Main_Log_Activity.objects.create(user=instance.company.company_name.username,details_of_activity=log_messages)
 
post_save.connect(log_activity_add_agent,sender=company_agent) 
post_delete.connect(log_activity_delete_agent,sender=company_agent)   


##creditionals
# ###############google########################
# username:
# pichai_sundararajan
# passwprd:
# pichai
# email
# google@gmail.com
###################

# ###############Amazon########################
# username:
# jeff_bezos
# passwprd:
# jeff
# email
# amazon@gmail.com
# ###############flipkart########################
# username:
# kalyan_krishnamurthy
# passwprd:
# kalyan
# email
# flipkart@gmail.com

mode_fin_task/company/views.py
from django.shortcuts import render
from company.models import *
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.urls import reverse_lazy

#login related method
def user_login(request):
    context={}
    if request.method=="POST":
        username=request.POST["username"]
        password=request.POST["password"]
        user= authenticate(request,username=username,password=password)
        if user:
            login(request, user)
            if request.GET.get('next', None):
                return HttpResponseRedirect(request.GET['next'])
            log_messages="%s user is login"%(username)  
            Main_Log_Activity.objects.create(user=username,log_in_time=timezone.now(),details_of_activity=log_messages)    
            return HttpResponseRedirect(reverse('company_wise_list'))
        else:
            context["error"]="Please Provide the valid username and password!!"
            return render(request,"auth/login_two.html",context)     
    else:
        return render(request,"auth/login_two.html",context)
#log_out related method
def user_logout(request):
    if request.method=="POST":
        username=request.user
        log_messages="%s user is logout"%(username)  
        Main_Log_Activity.objects.create(user=username,log_out_time=timezone.now(),details_of_activity=log_messages)    
        logout(request)
        return HttpResponseRedirect(reverse("user_login"))
#recovery the creditional using the emaail id
def recovery_creditional(request):
    context = {}
    if request.method == 'POST':
        email=request.POST["email"]
        username=request.POST["username"]
        password=request.POST["password"]
        confirm_password=request.POST["confirm_password"]
        if password!=confirm_password:
            context["error"]="password and confirm is not same!!"
            return render(request,"auth/recovery_creditional.html",context)
        else: 
            try:
                user_obj=User.objects.get(email=email)
                user_obj.username=username
                user_obj.set_password(password)
                user_obj.save()
                return HttpResponseRedirect(reverse("user_login"))
            except Exception as e:
                context["error"]=str(e)
                return render(request,"auth/recovery_creditional.html",context)    
    else:
        return render(request, "auth/recovery_creditional.html", context)
#showing the employee data         
@login_required(login_url="/login/")
def company_wise_list(request):
    context = {}
    company_obj=Company.objects.get(company_name__username=request.user)
    context['company_obj'] = company_obj
    context['title'] = 'Agent'
    return render(request, 'company/comapny_wise_profile.html', context)    
#showing activity of admin
@login_required(login_url="/login/")
def activity_log(request):
    context={}
    main_log_activity_obj=Main_Log_Activity.objects.filter(user=request.user)
    context['main_log_activity_obj'] = main_log_activity_obj
    context['title'] = 'Details of admin activity'
    return render(request, 'company/admin_activity_log.html', context)

mode_fin_task/mode_fin_task/templates/base.html
{% load static %}
<html>
    <head>
        <title>Employee Management System</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
    <body>
        {% include 'header.html'  %}
        <!-- <h1>EMS</h1> -->
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

mode_fin_task/mode_fin_task/templates/company/admin_activity_log.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-sm-12">
        <p>
            <div class="float-left"><h3>{{title}}</h3></div>
        </p>
        <div class="table-responsive-sm">
        {% if main_log_activity_obj %}
            <table class="table table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th class="text-center">Admin Name</th>
                        <th class="text-center">Activity Created date</th>
                        <th class="text-center">Activity Details</th>
                        <th class="text-center">Login</th>
                        <th class="text-center">LogOut</th>
                    </tr>
                </thead>
                <tbody>
                {% for log_activity_obj in main_log_activity_obj %}
                    <tr>
                        <td class="text-center">
                            <span class="badge badge-default">{{log_activity_obj.user}}</span>
                        </td>
                        <td class="text-center">
                            <span class="badge badge-default">{{log_activity_obj.created_date}}</span>
                        </td>
                        <td class="text-center">
                            <span class="badge badge-default">{{log_activity_obj.details_of_activity}}</span>
                        </td>
                        <td class="text-center">
                            <span class="badge badge-default">{{log_activity_obj.log_in_time}}</span>
                        </td>
                        <td class="text-center">
                            <span class="badge badge-default">{{log_activity_obj.log_out_time}}</span>
                        </td>

                    </tr>
                {% endfor %}
                </tbody>
                </table>
        </div>
        {% else %}
            <p class="text-center" >No log activity data available</p>
        {% endif %}
    </div>
</div>
{% endblock content %}

mode_fin_task/mode_fin_task/templates/company/comapny_wise_profile.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-sm-8">
        <p>
            <div class="float-left"><h3>List of {{title}}</h3></div>
        </p>
        <div class="table-responsive-sm">
        {% if company_obj %}
            <table class="table table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th class="text-center">Company Name</th>
                        <th class="text-center">Agent Name</th>
                        <th class="text-center">No Of Call Attended</th>
                        <th class="text-center">Time Spend</th>
                    </tr>
                </thead>
                <tbody>
                {% for agent_obj in company_obj.company_agent_set.all %}
                    <tr>
                        <td class="text-center">
                            <span class="badge badge-default">{{company_obj.brand_name}}</span>
                        </td>
                        <td class="text-center">
                            <span class="badge badge-default">{{agent_obj.company_agent_name}}</span>
                        </td>
                        <td class="text-center">
                            <span class="badge badge-default">{{agent_obj.no_of_call_attended}}</span>
                        </td>
                        <td class="text-center">
                            <span class="badge badge-default">{{agent_obj.total_time_spent_for_call_attended}}</span>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
        </div>
        {% else %}
            <p class="text-center" >No Company data available</p>
        {% endif %}
    </div>
</div>
{% endblock content %}

mode_fin_task/mode_fin_task/templates/header.html
<div class="navbar navbar-expand-lg navbar-light bg-light">
   <span class="navbar-brand mb-0 h1">Company Agent Management</span>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
         <li class="nav-item">
            <a class="nav-link" href="{% url 'company_wise_list' %}">
            {{"Agent Details" | capfirst}}
            </a>
         </li>
         <li class="nav-item">
            <a class="nav-link" href="{% url 'activity_log' %}">
            {{"Activity Log" | capfirst}} 
            <span class="badge badge-primary badge-pill "></span>
            </a>
         </li>
      </ul>
   </div>
   <div>    
       <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'user_logout' %}">
        {% csrf_token %}
        <span class="mr-sm-2">{{request.user.company.brand_name}}({{request.user.first_name}})</spans>
        <a href="#">
        </a>
        <input type="submit" class="btn btn-outline-danger my-2 my-sm-0" value="Logout">
    </form>
   </div>
   </div>